server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # 启动网关功能,允许路由到指定路径
          enabled: true
          # 允许服务器名称小写
          lower-case-service-id: true
      routes: # 开始配置路由
        - id: gateway-sys
          uri: lb://sys-service
          predicates:
            - Path=/v1/**
        - id: gateway-resource  #设置路由名称,和其他任何配置无关
          # 配置路由目标服务器名称:resource-server,和nacos中注册的名称一致
          # lb是Load Balance的缩写,意思是负载均衡
          uri: lb://resource-server
          # 路由路径的配置
          # 下面的配置表示当访问localhost:9000/image/a.jpg时
          # 相当于访问了resource-server服务器的相同路径
          # 既访问了: localhost:8899/image/a.jpg
          predicates:
            - Path=/image/**